# Default values for ocellusai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace where resources will be deployed
namespaceOverride: ""

## Operator configuration
operator:
  enabled: true

  image:
    repository: quay.io/ocellusai/operator
    tag: v0.10.5
    pullPolicy: IfNotPresent

  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # ServiceAccount configuration
  serviceAccount:
    create: true
    name: ocellusai-operator

  # RBAC configuration
  rbac:
    create: true

## CRD installation
crd:
  # Install CRD as part of the chart
  install: true

## Web Service Deployment configuration
service:
  enabled: true

  image:
    repository: quay.io/ocellusai/ocellusai-mini
    tag: v0.10.5
    pullPolicy: IfNotPresent

  replicas: 1
  port: 8080

  resources:
    requests:
      cpu: "2"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "1Gi"

  # Node affinity
  nodeSelector: {}

  # Tolerations for node taints
  tolerations: []

  # API configuration
  apiKey: "your-api-key-here"

  # Model configuration
  modelName: "model-name-here"
  baseUrl: "api-model-baseUrl-here"

  # Metrics configuration
  metricServerUrl: "http://prometheus-server.monitoring.svc.cluster.local"
  jobName: "ocellusai"
  
  # Cost Configuration
  # Optional parameters - Default values represent average annual costs per 1 CPU core and 1GB memory across major public cloud providers (cost per year)
  costPerCPU: "120.0"
  costPerMEM: "36.0"

  # Kubernetes Service
  k8sService:
    type: ClusterIP
    port: 80
    targetPort: 8080
    sessionAffinity: ClientIP
    sessionAffinityTimeout: 10800

  # Ingress configuration
  ingress:
    enabled: false
    className: "className"
    host: "domain.com"
    path: /
    pathType: Prefix
    tls: []