{{- if .Values.service.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocellusai-config
  namespace: {{ include "ocellusai.namespace" . }}
data:  
  # AI Configuration
  MODEL_NAME: {{ .Values.service.modelName | quote }}
  BASE_URL: {{ .Values.service.baseUrl | quote }}
  
  # Metrics Configuration
  METRIC_SERVER_URL: {{ .Values.service.metricServerUrl | quote }}
  JOB_NAME: {{ .Values.service.jobName | quote }}
  
  # Cost Configuration
  COST_PER_CPU: {{ .Values.service.costPerCPU | quote }}
  COST_PER_MEM: {{ .Values.service.costPerMEM | quote }}
  
{{- end }}
