{{- if .Values.service.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocellusai-config
  namespace: {{ include "ocellusai.namespace" . }}
data:  
  # AI Configuration
  modelName: {{ .Values.service.modelName | quote }}
  baseUrl: {{ .Values.service.baseUrl | quote }}
  
  # Metrics Configuration
  metricServerUrl: {{ .Values.service.metricServerUrl | quote }}
  JobName: {{ .Values.service.jobName | quote }}
  
  # Cost Configuration
  costPerCPU: {{ .Values.service.costPerCPU | quote }}
  costPerMEM: {{ .Values.service.costPerMEM | quote }}
  
{{- end }}
