{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ocellusai.serviceAccountName" . }}
  namespace: {{ include "ocellusai.namespace" . }}
{{- end }}
